# Generated by Django 3.2.5 on 2021-07-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(default='537d9df9-f022-11eb-b47f-2f85e351cbe3', max_length=20, unique=True),
        ),
    ]
