# Generated by Django 3.2.5 on 2021-07-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_alter_provider_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.CharField(default='a4a63e69-f023-11eb-afa5-86ca8cdf94f5', max_length=20, unique=True),
        ),
    ]
