# Generated by Django 3.2.5 on 2021-07-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='currency',
            field=models.CharField(default='Php', max_length=10),
        ),
    ]
